version: '3'

services:

  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: docker_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin:latest
    restart: "no"
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"

volumes:
  mysql-data:
